<?php /** @var $this Webguys_EasytemplateNewsletter_Block_Template */ ?>
<table border="0" cellpadding="0" cellspacing="0" width="100%">
    <tr>
        <td bgcolor="#ffffff" align="center" style="padding: 10px 15px 10px 15px;" class="section-padding">
            <table border="0" cellpadding="0" cellspacing="0" width="500" class="responsive-table">
                <tr>
                    <td>
                        <table width="100%" border="0" cellspacing="0" cellpadding="0">
                            <tr>
                                <!-- HERO IMAGE -->
                                <td class="padding-copy">
                                    <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                        <tr>
                                            <td style="padding: 20px 0 0 0;">
                                                <img src="<?php echo $this->getImage() ?>"
                                                    width="500" height="<?php echo $this->getImageHeight() ?>" border="0" alt="<?php echo $this->getImageAltText() ?>"
                                                    style="display: block; padding: 0; color: #266e9c; text-decoration: none; font-family: Helvetica, arial, sans-serif; font-size: 16px;"
                                                    class="img-max">
                                            </td>
                                        </tr>
                                    </table>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>