<?php /** @var $this Webguys_EasytemplateNewsletter_Block_Template */ ?>
<?php $tableInformation = explode(PHP_EOL, $this->getTableInformation()); ?>
<?php $i = 0; ?>
<!-- TWO COLUMN SECTION -->
<table border="0" cellpadding="0" cellspacing="0" width="100%">
    <tr>
        <td bgcolor="#ffffff" align="center" style="padding: 15px 15px 15px 15px;" class="section-padding">
            <table border="0" cellpadding="0" cellspacing="0" width="500" class="responsive-table">
                <?php foreach ($tableInformation as $row) : ?>
                    <?php list($left, $right) = explode(';', $row, 2); ?>
                    <tr>
                        <?php if ($i == 0) : ?>
                            <td style="padding: 10px 0 0 0; border-top: 1px dashed #aaaaaa;">
                        <?php elseif ($i == count($tableInformation) - 1) : ?>
                            <td style="border-bottom: 1px dashed #aaaaaa;">
                        <?php else : ?>
                            <td>
                        <?php endif; ?>
                            <!-- TWO COLUMNS -->
                            <table cellspacing="0" cellpadding="0" border="0" width="100%">
                                <tr>
                                    <td valign="top" class="mobile-wrapper">
                                        <!-- LEFT COLUMN -->
                                        <table cellpadding="0" cellspacing="0" border="0" width="47%" style="width: 47%;" align="left">
                                            <tr>
                                                <td style="padding: 0 0 10px 0;">
                                                    <table cellpadding="0" cellspacing="0" border="0" width="100%">
                                                        <tr>
                                                            <td align="left" style="font-family: Arial, sans-serif; color: #333333; font-size: 16px;"><?php echo $left ?></td>
                                                        </tr>
                                                    </table>
                                                </td>
                                            </tr>
                                        </table>
                                        <!-- RIGHT COLUMN -->
                                        <table cellpadding="0" cellspacing="0" border="0" width="47%" style="width: 47%;" align="right">
                                            <tr>
                                                <td style="padding: 0 0 10px 0;">
                                                    <table cellpadding="0" cellspacing="0" border="0" width="100%">
                                                        <tr>
                                                            <td align="right" style="font-family: Arial, sans-serif; color: #333333; font-size: 16px;"><?php echo $right ?></td>
                                                        </tr>
                                                    </table>
                                                </td>
                                            </tr>
                                        </table>
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                    <?php $i++; ?>
                <?php endforeach; ?>
            </table>
        </td>
    </tr>
</table>